const test=require('node:test'),assert=require('node:assert/strict'),ExcelJS=require('exceljs');
const {buildTemplate,workbookToCsv,exampleRows}=require('../services/historicalWorkbook');
const {validateImport,createHistoricalSeason}=require('../services/historicalSeasonImport');
const masters={drivers:[{id:11,name:'Alpha',viewF1:true},{id:12,name:'Beta',roleFormerF1:true}],teams:[{id:4,name:'McLaren',accentColor:'#ffa500'}],tracks:[{id:9,name:'Bahrain International Circuit',country:'Bahrain'}]};
let bytes;
test('Template has fresh master dropdowns, an empty input sheet, and isolated examples',async()=>{
 bytes=await buildTemplate(masters);const book=new ExcelJS.Workbook();await book.xlsx.load(bytes);
 assert.deepEqual(book.worksheets.map(s=>s.name),['Start','Ergebnisse','Beispiel','Fahrer','Teams','Strecken']);
 assert.equal(book.getWorksheet('Ergebnisse').getCell('D2').value,null);
 assert.equal(book.getWorksheet('Ergebnisse').getCell('D5001').dataValidation.formulae[0],'FahrerAuswahl');
 assert.equal(book.getWorksheet('Fahrer').getCell('A2').value,'11 · Alpha');
 assert.equal(book.getWorksheet('Beispiel').getCell('D2').value,'11 · Alpha');
 await assert.rejects(workbookToCsv(bytes),/Ergebnisse ist leer/);
});
test('Filled workbook imports names by stable ID, real Excel dates and separate session statuses',async()=>{
 const book=new ExcelJS.Workbook();await book.xlsx.load(bytes||await buildTemplate(masters));
 exampleRows(masters).forEach((values,i)=>{const row=[...values];row[1]=new Date(`${row[1]}T00:00:00Z`);book.getWorksheet('Ergebnisse').getRow(i+2).values=row;});
 const csv=await workbookToCsv(await book.xlsx.writeBuffer());const plan=validateImport(csv,masters);
 assert.equal(plan.rows.length,4);assert.equal(plan.rows[0].fahrer_id,11);assert.equal(plan.rows[0].datum,'2020-03-01');
 assert.equal(plan.rows[2].status,'');assert.equal(plan.rows[3].status,'DNF');
 book.getWorksheet('Ergebnisse').getCell('I2').value={formula:'1+1',result:2};await assert.rejects(workbookToCsv(await book.xlsx.writeBuffer()),/Werte statt Formeln/);
});
test('Imported points and awards reconcile with career, driver master and constructors statistics',async()=>{
 const {buildCareerStatistics}=require('../services/careerStatistics');const {summarizeDriverEntries}=require('../services/driverStats');const {buildSeasonData}=require('../services/standings');
 const {createCsv}=require('../services/csv'),{HEADERS}=require('../services/historicalSeasonImport');
 const rows=exampleRows(masters,false);rows[3][7]=2;rows[3][8]=7;rows[3][9]='';
 const plan=validateImport(createCsv([HEADERS,...rows]),masters),created={};let id=100;
 const models=Object.fromEntries(['Season','SeasonTeam','SeasonDriver','SeasonLineupEntry','SeasonDriverStint','GrandPrixResult','GrandPrixResultEntry','F1RaceLineupEntry','RaceEvent'].map(name=>[name,{create:async data=>{const row={id:++id,...data};(created[name]||=[]).push(row);return row;}}]));models.League={findByPk:async()=>({id:1})};models.Season.findAll=async()=>[];
 const league={id:1,slug:'sonntag',name:'Sonntag'};
 const season=await createHistoricalSeason({name:'Historisch',league,masters,plan,reservePointsForConstructors:true},models,{LOCK:{UPDATE:'UPDATE'}});
 const entries=created.GrandPrixResultEntry.map(entry=>({...entry,grandPrixResult:{...created.GrandPrixResult.find(race=>race.id===entry.GrandPrixResultId),league,seasonRecord:season}}));
 const careers=buildCareerStatistics(masters.drivers,entries);const beta=careers.find(driver=>driver.id===12).seasons[0];
 assert.equal(beta.points,32);assert.equal(beta.wins,1);assert.equal(beta.poles,1);assert.equal(beta.driverOfTheDays,1);
 assert.equal(summarizeDriverEntries(entries.filter(entry=>entry.DriverId===12)).f1.points,beta.points);
 const drivers=masters.drivers.map(driver=>({...driver,team:created.SeasonTeam[0]}));
 const races=created.GrandPrixResult.map(race=>({...race,entries:entries.filter(entry=>entry.GrandPrixResultId===race.id)}));
 const stints=created.SeasonDriverStint.map(stint=>({...stint,driver:drivers.find(driver=>driver.id===stint.DriverId),seasonTeam:created.SeasonTeam[0]}));
 const data=buildSeasonData(league,races,drivers,created.F1RaceLineupEntry,season,stints);
 assert.equal(data.teamStandings[0].points,58);assert.equal(data.driverStandings.find(row=>row.driver.name==='Beta').points,32);
});
