const express = require('express');
const asyncHandler = require('../services/asyncHandler');
const adminController = require('../controllers/adminController');
const raceEditorController = require('../controllers/raceEditorController');
const seriesEditorController = require('../controllers/seriesEditorController');
const { requireAdmin } = require('../middleware/auth');
const upload = require('../middleware/upload');

const router = express.Router();
router.use(requireAdmin);
router.get('/', asyncHandler(adminController.dashboard));
router.get('/race-editor', asyncHandler(raceEditorController.show));
router.post('/race-editor/seasons', asyncHandler(raceEditorController.createSeason));
router.post('/race-editor/races', asyncHandler(raceEditorController.createRace));
router.post('/race-editor/import-calendar', asyncHandler(raceEditorController.importCalendar));
router.post('/race-editor/:raceId/settings', asyncHandler(raceEditorController.updateRace));
router.delete('/race-editor/:raceId', asyncHandler(raceEditorController.removeRace));
router.post('/race-editor/:raceId', asyncHandler(raceEditorController.save));
router.get('/season-progress/:discipline(lmu|wdl)', asyncHandler(seriesEditorController.show));
router.post('/season-progress/:discipline(lmu|wdl)/seasons', asyncHandler(seriesEditorController.createSeason));
router.post('/season-progress/:discipline(lmu|wdl)/races', asyncHandler(seriesEditorController.createRace));
router.post('/season-progress/:discipline(lmu|wdl)/import-calendar', asyncHandler(seriesEditorController.importCalendar));
router.post('/season-progress/:discipline(lmu|wdl)/:raceId/settings', asyncHandler(seriesEditorController.updateRace));
router.delete('/season-progress/:discipline(lmu|wdl)/:raceId', asyncHandler(seriesEditorController.removeRace));
router.post('/season-progress/:discipline(lmu|wdl)/:raceId', asyncHandler(seriesEditorController.save));
router.get('/:resource', asyncHandler(adminController.list));
router.get('/:resource/new', asyncHandler(adminController.createForm));
router.post('/:resource', upload.single('image'), asyncHandler(adminController.create));
router.get('/:resource/:id/edit', asyncHandler(adminController.editForm));
router.put('/:resource/:id', upload.single('image'), asyncHandler(adminController.update));
router.delete('/:resource/:id', asyncHandler(adminController.remove));

module.exports = router;
