const express = require('express');
const asyncHandler = require('../services/asyncHandler');
const adminController = require('../controllers/adminController');
const raceEditorController = require('../controllers/raceEditorController');
const seriesEditorController = require('../controllers/seriesEditorController');
const teamRosterController = require('../controllers/teamRosterController');
const f1RaceLineupController = require('../controllers/f1RaceLineupController');
const lmuRaceLineupController = require('../controllers/lmuRaceLineupController');
const seasonSetupController = require('../controllers/seasonSetupController');
const tableHubController = require('../controllers/tableHubController');
const { requireAdmin } = require('../middleware/auth');
const upload = require('../middleware/upload');

const router = express.Router();
router.use(requireAdmin);
router.get('/', asyncHandler(adminController.dashboard));
router.get('/team-rosters/:discipline(f1|lmu)', asyncHandler(teamRosterController.show));
router.post('/team-rosters/:discipline(f1|lmu)', asyncHandler(teamRosterController.create));
router.post('/team-rosters/:discipline(f1|lmu)/:rosterId/drivers', asyncHandler(teamRosterController.addDriver));
router.delete('/team-rosters/:discipline(f1|lmu)/assignments/:assignmentId', asyncHandler(teamRosterController.removeDriver));
router.delete('/team-rosters/:discipline(f1|lmu)/:rosterId', asyncHandler(teamRosterController.removeRoster));
router.get('/f1-race-lineup', asyncHandler(f1RaceLineupController.show));
router.post('/f1-race-lineup/:raceId', asyncHandler(f1RaceLineupController.save));
router.get('/lmu-race-lineup', asyncHandler(lmuRaceLineupController.show));
router.post('/lmu-race-lineup/:raceId', asyncHandler(lmuRaceLineupController.save));
router.get('/season-setup', asyncHandler(seasonSetupController.show));
router.post('/season-setup/seasons', asyncHandler(seasonSetupController.createSeason));
router.post('/season-setup/:seasonId/profile', asyncHandler(seasonSetupController.updateSeasonProfile));
router.post('/season-setup/:seasonId/calendar', asyncHandler(seasonSetupController.addCalendarEvent));
router.post('/season-setup/:seasonId/cars', asyncHandler(seasonSetupController.assignF1Cars));
router.get('/table-hub', asyncHandler(tableHubController.show));
router.get('/race-editor', asyncHandler(raceEditorController.show));
router.post('/race-editor/seasons', asyncHandler(raceEditorController.createSeason));
router.post('/race-editor/races', asyncHandler(raceEditorController.createRace));
router.post('/race-editor/import-calendar', asyncHandler(raceEditorController.importCalendar));
router.post('/race-editor/:raceId/settings', asyncHandler(raceEditorController.updateRace));
router.delete('/race-editor/:raceId', asyncHandler(raceEditorController.removeRace));
router.post('/race-editor/:raceId', asyncHandler(raceEditorController.save));
router.get('/season-progress/:discipline(lmu|wdl)', asyncHandler(seriesEditorController.show));
router.post('/season-progress/:discipline(lmu|wdl)/seasons', asyncHandler(seriesEditorController.createSeason));
router.post('/season-progress/:discipline(lmu|wdl)/races', asyncHandler(seriesEditorController.createRace));
router.post('/season-progress/:discipline(lmu|wdl)/import-calendar', asyncHandler(seriesEditorController.importCalendar));
router.post('/season-progress/:discipline(lmu|wdl)/:raceId/settings', asyncHandler(seriesEditorController.updateRace));
router.delete('/season-progress/:discipline(lmu|wdl)/:raceId', asyncHandler(seriesEditorController.removeRace));
router.post('/season-progress/:discipline(lmu|wdl)/:raceId', asyncHandler(seriesEditorController.save));
router.get('/:resource', asyncHandler(adminController.list));
router.get('/:resource/new', asyncHandler(adminController.createForm));
router.post('/:resource', upload.single('image'), asyncHandler(adminController.create));
router.get('/:resource/:id/edit', asyncHandler(adminController.editForm));
router.put('/:resource/:id', upload.single('image'), asyncHandler(adminController.update));
router.delete('/:resource/bulk', asyncHandler(adminController.bulkRemove));
router.delete('/:resource/:id', asyncHandler(adminController.remove));

module.exports = router;
