const { Op } = require('sequelize');
const m = require('../models');
const s = require('../services/lmuSeason');
const weekend = require('../services/lmuWeekend');
const { saveImage, deleteUpload } = require('../services/imageStorage');
const base='/admin';
const flash=(req,type,message)=>{req.session.flash={type,message};};
async function context(query={}){
 const leagues=await m.League.findAll({where:{type:'lmu'},order:[['sortOrder','ASC'],['id','ASC']]});
 const requested=query.season?await m.Season.findByPk(query.season):null;
 const league=leagues.find(l=>l.id===Number(query.league))||leagues.find(l=>requested?.leagueType==='lmu'&&l.slug===requested.scopeSlug)||leagues[0]||null;
 const seasons=league?await m.Season.findAll({where:{leagueType:'lmu',scopeSlug:league.slug},order:[['id','DESC']]}):[];
 const season=seasons.find(row=>row.id===Number(query.season))||seasons.find(row=>row.status==='active')||seasons[0]||null;
 return {leagues,league,seasons,season};
}
exports.calendars=async(req,res)=>{
 const calendars=await m.LmuCalendar.findAll({order:[['name','ASC']]});const selected=calendars.find(c=>c.id===Number(req.query.calendar))||null;
 res.render('admin/lmu-calendars',{title:'Zentrale LMU-Rennkalender',calendars,selected,draft:req.session.lmuCalendarDraft||null,localDateTime:require('../services/calendarTime').localDateTime});delete req.session.lmuCalendarDraft;
};
exports.saveCalendar=async(req,res)=>{
 try{const name=String(req.body.name||'').trim();if(!name||name.length>255)throw new Error('Bitte einen Kalendernamen eingeben.');const rounds=s.roundsFrom(req.body.rounds);
 await m.sequelize.transaction(async transaction=>{if(req.params.id){const record=await m.LmuCalendar.findByPk(req.params.id,{transaction,lock:transaction.LOCK.UPDATE});if(!record)throw new Error('Kalender nicht gefunden.');await record.update({name,rounds,isActive:req.body.isActive==='on'},{transaction});}else await m.LmuCalendar.create({name,rounds,isActive:req.body.isActive==='on'},{transaction});});flash(req,'success','Kalender gespeichert. Bereits erstellte Saisons behalten ihre eigenen Termine.');
 }catch(error){req.session.lmuCalendarDraft={...req.body,id:req.params.id};flash(req,'error',error.message);}
 res.redirect(`${base}/lmu-calendars${req.params.id?'?calendar='+req.params.id:''}`);
};
exports.deleteCalendar=async(req,res)=>{try{await m.sequelize.transaction(async transaction=>{const record=await m.LmuCalendar.findByPk(req.params.id,{transaction,lock:transaction.LOCK.UPDATE});if(!record)throw new Error('Kalender nicht gefunden.');if(await m.Season.count({where:{LmuCalendarId:record.id},transaction}))throw new Error('Der Kalender wird von einer Saison verwendet. Stattdessen deaktivieren.');await record.destroy({transaction});});flash(req,'success','Kalender gelöscht.');}catch(error){flash(req,'error',error.message);}res.redirect(`${base}/lmu-calendars`);};
exports.games=async(req,res)=>{const games=await m.LmuGame.findAll({order:[['name','ASC']]});res.render('admin/lmu-games',{title:'LMU-Spiel und Logo',games,selected:games.find(g=>g.id===Number(req.query.game))||null});};
exports.saveGame=async(req,res)=>{let path;try{const name=String(req.body.name||'').trim();if(!name||name.length>255)throw new Error('Bitte einen Spielnamen eingeben.');const game=req.params.id?await m.LmuGame.findByPk(req.params.id):null;if(req.params.id&&!game)throw new Error('Spiel nicht gefunden.');if(req.file)path=await saveImage(req.file);const values={name,isActive:req.body.isActive==='on',logoPath:path||game?.logoPath||null};if(game)await game.update(values);else await m.LmuGame.create(values);flash(req,'success','LMU-Spiel gespeichert.');}catch(error){if(path)await deleteUpload(path);flash(req,'error',error.message);}res.redirect(`${base}/lmu-games`);};
exports.setup=async(req,res)=>{const data=await context(req.query);const [calendars,games,schemes,teams,drivers]=await Promise.all([m.LmuCalendar.findAll({where:{isActive:true}}),m.LmuGame.findAll({where:{isActive:true}}),m.PointsScheme.findAll({where:{discipline:'lmu'}}),m.Team.findAll({where:{discipline:'lmu',LeagueId:null},order:[['name','ASC']]}),m.Driver.findAll({where:s.lmuWhere,order:[['name','ASC']]})]);res.render('admin/lmu-season-setup',{title:'LMU-Saison erstellen',...data,calendars,games,schemes,teams,drivers,draft:req.session.lmuSetupDraft||{}});};
exports.createSeason=async(req,res)=>{try{const season=await s.createSeason(req.body);delete req.session.lmuSetupDraft;flash(req,'success','LMU-Saison mit Kalender und Fahrerbesetzung erstellt.');return res.redirect(`${base}/lmu-seasons?season=${season.id}`);}catch(error){req.session.lmuSetupDraft=req.body;flash(req,'error',error.message);res.redirect(`${base}/lmu-season-setup?league=${Number(req.body.LeagueId)||''}`);}};
exports.seasons=async(req,res)=>{const data=await context(req.query);const [games,schemes]=await Promise.all([m.LmuGame.findAll(),m.PointsScheme.findAll({where:{discipline:'lmu'}})]);res.render('admin/lmu-seasons',{title:'LMU-Saison bearbeiten / löschen',...data,games,schemes});};
exports.updateSeason=async(req,res)=>{try{await m.sequelize.transaction(async transaction=>{const season=await s.seasonById(req.params.id,transaction,true);const league=await m.League.findOne({where:{type:'lmu',slug:season.scopeSlug},transaction,lock:transaction.LOCK.UPDATE});const name=String(req.body.name||'').trim();if(!name||name.length>255)throw new Error('Bitte einen Saisonname eingeben.');if(await m.Season.findOne({where:{leagueType:'lmu',scopeSlug:season.scopeSlug,name,id:{[Op.ne]:season.id}},transaction}))throw new Error('Diese Saison existiert bereits.');const [game,scheme]=await Promise.all([m.LmuGame.findByPk(req.body.LmuGameId,{transaction}),m.PointsScheme.findByPk(req.body.PointsSchemeId,{include:[{association:'allocations'}],transaction})]);if(!game||scheme?.discipline!=='lmu')throw new Error('LMU-Spiel und LMU-Punktesystem auswählen.');const schemeChanged=Number(season.PointsSchemeId)!==Number(scheme.id);await season.update({name,status:req.body.status==='active'?'active':'historical',isPublished:req.body.isPublished==='on',accentColor:s.color(req.body.accentColor),LmuGameId:game.id,gameName:game.name,PointsSchemeId:scheme.id,reservePointsForConstructors:req.body.reservePointsForConstructors==='on'},{transaction});await s.activate(season,league,transaction);const races=await m.GrandPrixResult.findAll({where:{SeasonId:season.id,discipline:'lmu'},include:[{association:'entries'}],transaction});for(const race of races.filter(r=>schemeChanged&&r.pointsMode!=='manual'&&r.raceType!=='sprint'))for(const entry of race.entries)await entry.update({points:s.points(scheme,entry)},{transaction});await s.syncRanks(transaction);});flash(req,'success','Saison gespeichert. Punkte nach dem gewählten System aktualisiert.');}catch(error){flash(req,'error',error.message);}res.redirect(`${base}/lmu-seasons?season=${req.params.id}`);};
exports.deleteSeason=async(req,res)=>{try{await m.sequelize.transaction(async transaction=>{const season=await s.seasonById(req.params.id,transaction,true);if(req.body.confirmName!==season.name)throw new Error('Zum Löschen bitte den exakten Saisonnamen eingeben.');const races=await m.GrandPrixResult.findAll({where:{SeasonId:season.id,discipline:'lmu'},transaction});const where={GrandPrixResultId:{[Op.in]:races.map(r=>r.id)}};await m.GrandPrixResultEntry.destroy({where,transaction});await m.F1RaceLineupEntry.destroy({where,transaction});for(const model of [m.RaceEvent,m.PenaltyEntry,m.SeasonDriverCarryOver,m.SeasonDriverStint,m.SeasonLineupEntry,m.SeasonDriver,m.SeasonTeam])await model.destroy({where:{SeasonId:season.id},transaction});await m.GrandPrixResult.destroy({where:{SeasonId:season.id,discipline:'lmu'},transaction});await season.destroy({transaction});await s.syncRanks(transaction);});await require('../services/championship').recalculateDriverRaceCounts();flash(req,'success','LMU-Saison und ihre Saisonergebnisse gelöscht. Fahrer, Teams und Autos bleiben erhalten.');}catch(error){flash(req,'error',error.message);}res.redirect(`${base}/lmu-seasons`);};
exports.drivers=async(req,res)=>{const data=await context(req.query);if(data.season)await s.ensureStructure(data.season.id);const [teams,drivers,stints,rounds]=data.season?await Promise.all([m.SeasonTeam.findAll({where:{SeasonId:data.season.id}}),m.Driver.findAll({where:s.lmuWhere,order:[['name','ASC']]}),m.SeasonDriverStint.findAll({where:{SeasonId:data.season.id},include:[{association:'driver'},{association:'seasonTeam'}],order:[['fromRound','ASC']]}),m.GrandPrixResult.findAll({where:{SeasonId:data.season.id,discipline:'lmu'},order:[['sortOrder','ASC']]})]):[[],[],[],[]];res.render('admin/lmu-driver-change',{title:'LMU-Fahrerwechsel',...data,teams,drivers,stints,rounds,selectedDriver:Number(req.query.driver)||null,nextRound:data.season?await s.nextRound(data.season.id):1});};
exports.changeDriver=async(req,res)=>{try{await s.ensureStructure(req.params.id);await s.changeDriver(req.params.id,req.body);flash(req,'success','LMU-Fahrerwechsel gespeichert. Künftige Aufstellungen werden mit der neuen Besetzung erstellt.');}catch(error){flash(req,'error',error.message);}res.redirect(`${base}/lmu-driver-change?season=${req.params.id}`);};
exports.weekend=async(req,res)=>{const data=await context(req.query);if(data.season)await s.ensureStructure(data.season.id);const races=data.season?await m.GrandPrixResult.findAll({where:{SeasonId:data.season.id,discipline:'lmu',raceType:'main'},order:[['sortOrder','ASC']]}):[];const current=races.find(r=>r.id===Number(req.query.race))||races.find(r=>!r.raceDate||r.raceDate>=require('../services/raceWeekend').berlinDate())||races.at(-1);const details=current?await weekend.load(current.id):null;res.render('admin/lmu-weekend',{title:'Rennwochenende LMU',...data,races,details,regularStatuses:require('../services/raceLineup').REGULAR_STATUSES,reserveStatuses:require('../services/raceLineup').RESERVE_STATUSES});};
for(const [name,action]of Object.entries({lineup:'saveLineup',attendance:'saveAttendance',results:'saveResults',reset:'reset'}))exports[name]=async(req,res)=>{let race;try{race=await m.GrandPrixResult.findByPk(req.params.id);await weekend[action](req.params.id,req.body);if(action==='saveResults'||action==='reset')await require('../services/championship').recalculateDriverRaceCounts();flash(req,'success','Rennwochenende gespeichert.');}catch(error){flash(req,'error',error.message);}res.redirect(`${base}/race-weekend/lmu?season=${race?.SeasonId||''}&race=${req.params.id}#${name==='lineup'?'anwesenheit':name==='attendance'?'ergebnisse':'ergebnisse'}`);};
exports.penalties=async(req,res)=>{const data=await context(req.query);const [drivers,entries,setting,rounds]=data.league?await Promise.all([m.Driver.findAll({where:{[Op.or]:[s.lmuWhere,{roleFormerLmu:true}]},order:[['name','ASC']]}),m.PenaltyEntry.findAll({where:{LeagueId:data.league.id},include:[{association:'driver'},{association:'season'}],order:[['awardedOn','DESC'],['id','DESC']]}),m.F1PenaltySetting.findOne({where:{LeagueId:data.league.id}}),data.season?m.GrandPrixResult.findAll({where:{SeasonId:data.season.id,discipline:'lmu'},order:[['sortOrder','ASC']]}):[]]):[[],[],null,[]];res.render('admin/lmu-penalties',{title:'LMU-Strafkartei',...data,drivers,entries,setting,rounds});};
exports.savePenalty=async(req,res)=>{try{await m.sequelize.transaction(async transaction=>{const season=await s.seasonById(req.body.SeasonId,transaction,true);const league=await m.League.findOne({where:{type:'lmu',slug:season.scopeSlug},transaction});const driver=await m.Driver.findByPk(req.body.DriverId,{transaction});if(!driver||!(driver.viewLmu||driver.roleLmuRegular||driver.roleLmuReserve||driver.roleFormerLmu))throw new Error('Bitte einen LMU-Fahrer wählen.');const round=s.number(req.body.roundNumber,'Runde');const race=await m.GrandPrixResult.findOne({where:{SeasonId:season.id,discipline:'lmu',sortOrder:round},transaction});if(!race)throw new Error('Runde nicht gefunden.');const date=String(req.body.awardedOn||race.raceDate||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date)throw new Error('Bitte ein gültiges Datum angeben.');const expires=new Date(date+'T12:00:00Z');expires.setUTCFullYear(expires.getUTCFullYear()+1);const isRaceBan=req.body.isRaceBan==='on';if(isRaceBan&&await m.GrandPrixResultEntry.count({where:{GrandPrixResultId:race.id},transaction}))throw new Error('Eine Rennsperre für ein abgeschlossenes Rennen erfordert zuerst das Zurücksetzen der Ergebnisse.');await m.PenaltyEntry.create({SeasonId:season.id,LeagueId:league.id,DriverId:driver.id,roundNumber:round,points:isRaceBan?0:s.number(req.body.points,'Strafpunkte',0),isRaceBan,reason:String(req.body.reason||'').slice(0,255),awardedOn:date,expiresOn:expires.toISOString().slice(0,10)},{transaction});});flash(req,'success','Strafe eingetragen. Rennsperren gelten im zugeordneten Rennwochenende.');}catch(error){flash(req,'error',error.message);}res.redirect(`${base}/lmu-penalty-ledger?season=${Number(req.body.SeasonId)||''}`);};
exports.removePenalty=async(req,res)=>{try{const entry=await m.PenaltyEntry.findByPk(req.params.id,{include:[{association:'league'}]});if(entry?.league?.type!=='lmu')throw new Error('LMU-Strafe nicht gefunden.');await entry.destroy();flash(req,'success','Strafe entfernt.');}catch(error){flash(req,'error',error.message);}res.redirect(`${base}/lmu-penalty-ledger`);};
exports.penaltySettings=async(req,res)=>{try{const league=await m.League.findByPk(req.body.LeagueId);if(league?.type!=='lmu')throw new Error('LMU-Liga nicht gefunden.');const [setting]=await m.F1PenaltySetting.findOrCreate({where:{LeagueId:league.id}});await setting.update({pointsLimit:s.number(req.body.pointsLimit,'Strafpunktelimit')});flash(req,'success','Strafpunktelimit gespeichert.');}catch(error){flash(req,'error',error.message);}res.redirect(`${base}/lmu-penalty-ledger?league=${Number(req.body.LeagueId)||''}`);};
module.exports.context=context;

exports.seasonCalendar=async(req,res)=>{const data=await context(req.query);const service=require('../services/lmuSeasonCalendar');const events=data.season?await service.eventsFor(data.season.id):[];res.render('admin/lmu-season-calendar',{title:'LMU-Saisonkalender',...data,events,version:service.version(events),localDateTime:require('../services/calendarTime').localDateTime});};
exports.saveSeasonCalendar=async(req,res)=>{try{await require('../services/lmuSeasonCalendar').save(req.params.id,req.body);flash(req,'success','Saisonkalender gespeichert.');}catch(error){flash(req,'error',error.message);}res.redirect('/admin/lmu-season-calendar?season='+req.params.id);};
